name: Build

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        pytest-major-version: ['2', '3', '4', '5', '6']
      fail-fast: true
    name: ${{ matrix.os }} - Pytest ${{ matrix.pytest-major-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pytest
        run: pip install pytest==${{ matrix.pytest-major-version }}.*

      - name: Build
        run: cmake -S example -B build -G "Unix Makefiles"

      - name: Test
        working-directory: build
        run: ctest
